DROP TABLE IF EXISTS `mtlog_userlog`;
CREATE TABLE `mtlog_userlog` (
 `id` bigint(10) unsigned NOT NULL AUTO_INCREMENT,
 `log_type` int(4) unsigned NOT NULL DEFAULT '1',
 `user_id` bigint(10) unsigned NOT NULL DEFAULT '0',
 `source_id` bigint(10) unsigned NOT NULL DEFAULT '0',
 `log_time` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
 `ip` varchar(30) CHARACTER SET utf8 NOT NULL DEFAULT '',
 `description` varchar(200) CHARACTER SET utf8 NOT NULL DEFAULT '',
 PRIMARY KEY (`id`),
 KEY `type` (`log_type`),
 KEY `user_id` (`user_id`),
 KEY `source_id` (`source_id`),
 KEY `log_time` (`log_time`),
 KEY `ip` (`ip`)
) ENGINE=MyISAM AUTO_INCREMENT=34 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci COMMENT='用户日志表，记录用户动作'
PARTITION BY RANGE (id) (PARTITION p0 VALUES LESS THAN (200000),  
PARTITION p1 VALUES LESS THAN (400000) , PARTITION p2 VALUES LESS THAN (600000) ,  
PARTITION p3 VALUES LESS THAN (800000) , PARTITION p4 VALUES LESS THAN (1000000) ,  
PARTITION p5 VALUES LESS THAN (1200000) , PARTITION p6 VALUES LESS THAN (1400000) ,  
PARTITION p7 VALUES LESS THAN (1600000) , PARTITION p8 VALUES LESS THAN (1800000) ,  
PARTITION p9 VALUES LESS THAN (2000000) , PARTITION p10 VALUES LESS THAN MAXVALUE);